
replicas: 1
registryUrl: ghcr.io/sharp-rmf
hostName: rmf-deployment-template.open-rmf.org

global:
  ROS_DOMAIN_ID: 15
  DDS_CONFIG_MOUNTPATH: /etc/cyclonedds
  DDS_CONFIG_VOLUME: cyclonedds-configmap
  DDS_ENV: CYCLONEDDS_URI
  DDS_CONFIG: /etc/cyclonedds/cyclonedds.xml
  DDS_CONFIG_FILE: site-specific-configs/galen/cyclonedds.xml
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
  
  BUILDING_CONFIG_VOLUME: building-configmap
  BUILDING_CONFIG_FILE_MOUNTPATH: /opt/rmf/install/rmf_demos_maps/share/rmf_demos_maps/office
  BUILDING_PICS_CONFIG_FILE_MOUNTPATH: /opt/rmf/install/rmf_demos_maps/share/rmf_demos_maps/office/pics

  RMF_USE_SIM_TIME: "false"
  RMF_BIDDING_TIME_WINDOW: "2.0"
  RMF_TRAJECTORY_VISUALIZER_LEVEL_NAME: "L1"
  RMF_BUILDING_MAP_SERVER_CONFIG_PATH: "/opt/rmf/install/rmf_demos_maps/share/rmf_demos_maps/office/galen.building.yaml"
  RMF_FAILOVER_MODE: "false"
  RMF_SERVER_URI: "ws://localhost:8001"

# Not in use
simulation:
  RMF_SIMULATION_MAP_NAME: "airport_terminal"
  RMF_SIMULATION_MAP_PACKAGE: "rmf_demos_maps"
  GAZEBO_VERSION: "11"
