# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "r3"
  fleet_manager:
    prefix: "edge.lionsbot.io"
    user: "ychi0003"
    password: "G7762#edswss09^"
  limits:
    linear: [0.4, 0.2] # velocity, acceleration
    angular: [0.3, 0.35] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.5 # radius in m
    vicinity: 0.6 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 760.0 # W
  recharge_threshold: 0.01 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: False
    delivery: False
    clean: True
    finishing_request: "nothing" # [park, charge, nothing]

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  R3-2200592-SCR:
    robot_config:
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      dock_home: [341.2186, 877.4262, 1.57079]
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: "ecb5e892-f006-44cb-9e77-66354c53500e"
        waypoint: "dock_home"
        orientation: 1.57079
      charger:
        waypoint: "dock_home"

reference_coordinates:
   rmf: [[17.0100, -43.7471],
         [31.5757, -49.0346],
         [26.1884, -39.9560],
         [22.4756, -42.8492]]
   robot: [[266.0, 284.0],
           [134.0, 573.0],
           [334.0, 476.0],
           [270.0, 398.0]]
