# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "leoScrub"
  fleet_manager:
    prefix: "dummy"
    user: "dummy"
    password: "dummy"
  limits:
    linear: [0.4, 0.2] # velocity, acceleration
    angular: [0.3, 0.35] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.5 # radius in m
    vicinity: 0.6 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 760.0 # W
  recharge_threshold: 0.01 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: False
    delivery: False
    clean: True
    finishing_request: "nothing" # [park, charge, nothing]

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  LB00090:
    robot_config:
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      entrance: [91, 55, 0]
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: "56a9d588-85bc-4dba-8090-1b3a35346c9b"
        waypoint: "entrance"
        orientation: 0
      charger:
        waypoint: "entrance"

reference_coordinates:
   rmf: [[-32.8815, -12.3584],
        [-31.4833, -18.1542],
        [-25.2648, -18.3353],
        [-24.1177, -11.3320]]
   robot: [[74.0, 343.0],
          [203.0, 312.0],
          [200.0, 195.0],
          [71.0, 174.0]]