apiVersion: v1
data:
  1.yaml: |- # Hospi
{{ .Files.Get "site-specific/nav_graphs/1.yaml" | indent 4}}
  3.yaml: |- # MiR
{{ .Files.Get "site-specific/nav_graphs/3.yaml" | indent 4}} 
  4.yaml: |- # Delta
{{ .Files.Get "site-specific/nav_graphs/4.yaml" | indent 4}}
  5.yaml: |- # Kabam
{{ .Files.Get "site-specific/nav_graphs/5.yaml" | indent 4}}
  6.yaml: |- # Lionbot r3
{{ .Files.Get "site-specific/nav_graphs/6.yaml" | indent 4}}
  7.yaml: |- # Lionbot leoscrub
{{ .Files.Get "site-specific/nav_graphs/7.yaml" | indent 4}}
  # 9.yaml: |- # Medisys
# {{ .Files.Get "site-specific/nav_graphs/9.yaml" | indent 4}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T11:59:12Z"
  name: nav-graph-configmap
  namespace: default
  resourceVersion: "1888520"
  uid: 09ba4a29-1b88-4f46-a83a-143dfb5bdd3a
