apiVersion: v1
data:
  1.yaml: |
    building_name: galen
    levels:
      L1:
        lanes:
        - - 0
          - 1
          - {speed_limit: 0}
        - - 1
          - 0
          - {speed_limit: 0}
        - - 2
          - 3
          - {speed_limit: 0}
        - - 3
          - 2
          - {speed_limit: 0}
        - - 3
          - 0
          - {speed_limit: 0}
        - - 0
          - 3
          - {speed_limit: 0}
        - - 0
          - 4
          - {speed_limit: 0}
        - - 4
          - 0
          - {speed_limit: 0}
        - - 4
          - 5
          - {speed_limit: 0}
        - - 5
          - 4
          - {speed_limit: 0}
        - - 5
          - 6
          - {speed_limit: 0}
        - - 6
          - 5
          - {speed_limit: 0}
        vertices:
        - - 10.75104449133459
          - -8.477440813303728
          - {name: n_try}
        - - 10.691288332598015
          - -10.838484294231613
          - {is_charger: true, is_parking_spot: true, name: m_start}
        - - 7.7578348678404
          - -8.559141324118706
          - {lift: A, lift_cabin: A, name: ''}
        - - 9.25317365927528
          - -8.574164765156997
          - {name: ''}
        - - 10.623176439800817
          - -5.558926388230256
          - {name: ''}
        - - 9.393448709868764
          - -5.6299079270684755
          - {name: ''}
        - - 7.7578348678404
          - -5.678438705703406
          - {lift: B, lift_cabin: B, name: ''}
      L5:
        lanes:
        - - 0
          - 1
          - {speed_limit: 0}
        - - 1
          - 0
          - {speed_limit: 0}
        - - 1
          - 2
          - {speed_limit: 0}
        - - 2
          - 1
          - {speed_limit: 0}
        - - 2
          - 3
          - {speed_limit: 0}
        - - 3
          - 2
          - {speed_limit: 0}
        - - 4
          - 5
          - {speed_limit: 0}
        - - 5
          - 4
          - {speed_limit: 0}
        - - 5
          - 6
          - {speed_limit: 0}
        - - 6
          - 5
          - {speed_limit: 0}
        - - 6
          - 2
          - {speed_limit: 0}
        - - 2
          - 6
          - {speed_limit: 0}
        - - 7
          - 8
          - {speed_limit: 0.3}
        - - 8
          - 7
          - {speed_limit: 0.3}
        - - 8
          - 9
          - {speed_limit: 0}
        - - 9
          - 8
          - {speed_limit: 0}
        - - 9
          - 10
          - {speed_limit: 0.3}
        - - 10
          - 9
          - {speed_limit: 0.3}
        - - 9
          - 11
          - {speed_limit: 0.3}
        - - 11
          - 9
          - {speed_limit: 0.3}
        vertices:
        - - 7.885886174730295
          - -8.489404643662908
          - {lift: A, lift_cabin: A, name: ''}
        - - 9.27093773641328
          - -8.537525519170543
          - {name: ''}
        - - 10.724306861903479
          - -8.612881635187517
          - {name: ''}
        - - 10.626437423426857
          - -10.739960762174007
          - {name: m_end}
        - - 7.919426967037175
          - -5.608888724814661
          - {lift: B, lift_cabin: B, name: ''}
        - - 9.583854114670721
          - -5.666721681447439
          - {name: ''}
        - - 10.779176738936108
          - -5.772092602393738
          - {name: n_lift}
        - - -33.89620228236757
          - -12.355129322975152
          - {is_charger: true, is_parking_spot: true, name: w4}
        - - -36.8850758292978
          - -12.238894798884214
          - {name: w3, spawn_robot_name: neuronbot2, spawn_robot_type: neuronbot}
        - - -36.953836111972905
          - -14.686245912479627
          - {name: ''}
        - - -39.240416867001876
          - -12.60438314539055
          - {name: w1, spawn_robot_name: missybot, spawn_robot_type: missy}
        - - -36.86293179355462
          - -16.407819777231285
          - {name: w2}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T11:59:12Z"
  name: nav-graph-configmap
  namespace: default
  resourceVersion: "1888520"
  uid: 09ba4a29-1b88-4f46-a83a-143dfb5bdd3a
