apiVersion: v1
data:
  1.yaml: |- # Hospi
{{ .Files.Get "1.yaml" | indent 4}}
  3.yaml: |- # MiR
{{ .Files.Get "3.yaml" | indent 4}} 
  4.yaml: |- # Delta
{{ .Files.Get "4.yaml" | indent 4}}
  5.yaml: |- # Kabam
{{ .Files.Get "5.yaml" | indent 4}}
  9.yaml: |- # Medisys
{{ .Files.Get "9.yaml" | indent 4}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T11:59:12Z"
  name: nav-graph-configmap
  namespace: default
  resourceVersion: "1888520"
  uid: 09ba4a29-1b88-4f46-a83a-143dfb5bdd3a
