---
apiVersion: v1
kind: Secret
metadata:
  name: rmf-web-rmf-server-secret
type: Opaque
stringData:
  DB_USER: "rmf-web-rmf-server"
  DB_PASSWORD: "rmf-web-rmf-server"
# these are initial values and updated post deploment