apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db
  labels:
    app: keycloak
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak
    tier: db
spec:
  selector:
    app: keycloak
    tier: db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      tier: db
  template:
    metadata:
      labels:
        app: keycloak
        tier: db
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: keycloak
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-db
      volumes:
        - name: keycloak-db
          persistentVolumeClaim:
            claimName: keycloak-db
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    tier: app
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: keycloak
    tier: app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      tier: app
  template:
    metadata:
      labels:
        app: keycloak
        tier: app
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:12.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_PASSWORD
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: {{ .Values.hostName | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.hostName | quote }}
      secretName: tls-certificate-secret-name

