---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_USER: "admin"
  KEYCLOAK_PASSWORD: "admin123"
  DB_USER: "keycloak"
  DB_PASSWORD: "keycloak"
# these are initial values and updated post deploment