---
apiVersion: v1
kind: Pod
namespace: 
metadata:
 name: kabam-fleet-adapter
spec:
 restartPolicy: Always
 hostNetwork: true
 containers:
   - name: kabam-fleet-adapter
     image: {{ .Values.registryUrl }}/rmf-deployment/rmf-fleet-adapter
     imagePullPolicy: Always
     env:
       - name: RMF_USE_SIM_TIME
         value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
       - name: {{ .Values.global.DDS_ENV | quote }}
         value: {{ .Values.global.DDS_CONFIG | quote }}
       - name: ROS_DOMAIN_ID
         value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
       - name: RMW_IMPLEMENTATION
         value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
       - name: RMF_FLEET_ADAPTER_CONTROL_TYPE
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_CONTROL_TYPE | quote }}
       - name: RMF_FLEET_ADAPTER_FLEET_NAME
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_FLEET_NAME | quote }}
       - name: RMF_FLEET_ADAPTER_NAV_GRAPH_FILE
         value: {{ .Values.global.NAV_GRAPH_MOUNT_PATH }}/{{ .Values.kabam.RMF_FLEET_ADAPTER_NAV_GRAPH_FILE}}
       - name: RMF_FLEET_ADAPTER_LINEAR_VELOCITY
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_LINEAR_VELOCITY | quote }}
       - name: RMF_FLEET_ADAPTER_ANGULAR_VELOCITY
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_ANGULAR_VELOCITY | quote }}
       - name: RMF_FLEET_ADAPTER_LINEAR_ACCELERATION
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_LINEAR_ACCELERATION | quote }}
       - name: RMF_FLEET_ADAPTER_ANGULAR_ACCELERATION
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_ANGULAR_ACCELERATION | quote }}
       - name: RMF_FLEET_ADAPTER_FOOTPRINT_RADIUS
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_FOOTPRINT_RADIUS | quote }}
       - name: RMF_FLEET_ADAPTER_VICINITY_RADIUS
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_VICINITY_RADIUS  | quote }}
       - name: RMF_FLEET_ADAPTER_DELAY_THRESHOLD
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_DELAY_THRESHOLD  | quote }}
       - name: RMF_FLEET_ADAPTER_RETRY_WAIT
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_RETRY_WAIT  | quote }}
       - name: RMF_FLEET_ADAPTER_DISCOVERY_TIMEOUT
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_DISCOVERY_TIMEOUT | quote }}
       - name: RMF_FLEET_ADAPTER_PERFORM_DELIVERIES
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_PERFORM_DELIVERIES | quote }}
       - name: RMF_FLEET_ADAPTER_PERFORM_LOOP
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_PERFORM_LOOP | quote }}
       - name: RMF_FLEET_ADAPTER_PERFORM_CLEANING
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_PERFORM_CLEANING | quote }}
       - name: RMF_FLEET_ADAPTER_BATTERY_VOLTAGE
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_BATTERY_VOLTAGE | quote  }}
       - name: RMF_FLEET_ADAPTER_BATTERY_CAPACITY
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_BATTERY_CAPACITY | quote }}
       - name: RMF_FLEET_ADAPTER_BATTERY_CHARGING_CURRENT
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_BATTERY_CHARGING_CURRENT | quote }}
       - name: RMF_FLEET_ADAPTER_MASS
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_MASS | quote }}
       - name: RMF_FLEET_ADAPTER_INERTIA
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_INERTIA | quote }}
       - name: RMF_FLEET_ADAPTER_FRICTION_COEFFICIENT
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_FRICTION_COEFFICIENT | quote }}
       - name: RMF_FLEET_ADAPTER_AMBIENT_POWER_DRAIN
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_AMBIENT_POWER_DRAIN  | quote }}
       - name: RMF_FLEET_ADAPTER_TOOL_POWER_DRAIN
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_TOOL_POWER_DRAIN  | quote }}
       - name: RMF_FLEET_ADAPTER_DRAIN_BATTERY
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_DRAIN_BATTERY | quote }}
       - name: RMF_FLEET_ADAPTER_RECHARGE_THRESHOLD
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_RECHARGE_THRESHOLD | quote }}
       - name: RMF_FLEET_ADAPTER_REVERSIBLE
         value: {{ .Values.kabam.RMF_FLEET_ADAPTER_REVERSIBLE | quote }}
     volumeMounts:
       - mountPath: /etc/cyclonedds
         name: cyclonedds-configmap
       - mountPath: /opt/rmf/install/rmf_demos_maps/share/rmf_demos_maps/maps/office/nav_graphs
         name: nav-graph-configmap
 volumes:
   - name: cyclonedds-configmap
     configMap:
       name: cyclonedds-configmap
   - name: nav-graph-configmap
     configMap:
       name: nav-graph-configmap