---
apiVersion: v1
kind: Pod
namespace: 
metadata:
 name: fleet-adapter-r3
spec:
 restartPolicy: Always
 hostNetwork: true
 containers:
   - name: fleet-adapter-r3
     image: {{ .Values.registryUrl }}/rmf-deployment/lionsbot-r3
     imagePullPolicy: Always
     env:
       - name: RMF_USE_SIM_TIME
         value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
       - name: {{ .Values.global.DDS_ENV | quote }}
         value: {{ .Values.global.DDS_CONFIG | quote }}
       - name: ROS_DOMAIN_ID
         value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
       - name: RMF_FLEET_ADAPTER
         value: {{ .Values.lionsbot.r3.RMF_FLEET_ADAPTER | quote }}
       - name: RMF_FLEET_ADAPTER_CONFIG_FILE
         value: {{ .Values.lionsbot.r3.RMF_FLEET_ADAPTER_CONFIG_FILE | quote }}
       - name: RMF_FLEET_ADAPTER_NAV_GRAPH_FILE
         value: {{ .Values.lionsbot.r3.RMF_FLEET_ADAPTER_NAV_GRAPH_FILE | quote }}
     volumeMounts:
       - mountPath: /etc/cyclonedds
         name: cyclonedds-configmap
       - mountPath: /opt/rmf/src/lionsbot/fleet_adapter_r3/maps/02office
         name: nav-graph-configmap
       - mountPath:  /opt/rmf/install/fleet_adapter_r3/share/fleet_adapter_r3
         name: lionsbot-r3-configmap
 volumes:
   - name: cyclonedds-configmap
     configMap:
       name: cyclonedds-configmap
   - name: nav-graph-configmap
     configMap:
       name: nav-graph-configmap
   - name: lionsbot-r3-configmap
     configMap:
       name: lionsbot-r3-configmap

---
apiVersion: v1
kind: Pod
namespace: 
metadata:
 name: fleet-adapter-leoscrub
spec:
 restartPolicy: Always
 hostNetwork: true
 containers:
   - name: fleet-adapter-leoscrub
     image: {{ .Values.registryUrl }}/rmf-deployment/lionsbot-leoscrub
     imagePullPolicy: Always
     env:
       - name: RMF_USE_SIM_TIME
         value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
       - name: {{ .Values.global.DDS_ENV | quote }}
         value: {{ .Values.global.DDS_CONFIG | quote }}
       - name: ROS_DOMAIN_ID
         value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
       - name: RMF_FLEET_ADAPTER
         value: {{ .Values.lionsbot.leoscrub.RMF_FLEET_ADAPTER | quote }}
       - name: RMF_FLEET_ADAPTER_CONFIG_FILE
         value: {{ .Values.lionsbot.leoscrub.RMF_FLEET_ADAPTER_CONFIG_FILE | quote }}
       - name: RMF_FLEET_ADAPTER_NAV_GRAPH_FILE
         value: {{ .Values.lionsbot.leoscrub.RMF_FLEET_ADAPTER_NAV_GRAPH_FILE | quote }}
       - name: RMF_FLEET_ADAPTER_SERVER_URI
         value: {{ .Values.lionsbot.leoscrub.RMF_FLEET_ADAPTER_SERVER_URI | quote }}
     volumeMounts:
       - mountPath: /etc/cyclonedds
         name: cyclonedds-configmap
       - mountPath: /opt/rmf/src/lionsbot/fleet_adapter_leoscrub/maps
         name: nav-graph-configmap
       - mountPath: /opt/rmf/install/fleet_adapter_leoscrub/share/fleet_adapter_leoscrub
         name: lionsbot-leoscrub-configmap
 volumes:
   - name: cyclonedds-configmap
     configMap:
       name: cyclonedds-configmap
   - name: nav-graph-configmap
     configMap:
       name: nav-graph-configmap
   - name: lionsbot-leoscrub-configmap
     configMap:
       name: lionsbot-leoscrub-configmap