---
apiVersion: v1
kind: Pod
namespace: 
metadata:
 name: mir-fleet-adapter
spec:
 restartPolicy: Always
 hostNetwork: true
 containers:
   - name: mir-fleet-adapter
     image: {{ .Values.registryUrl }}/rmf-deployment/medisys_mir
     imagePullPolicy: Always
     env:
       - name: RMF_USE_SIM_TIME
         value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
       - name: {{ .Values.global.DDS_ENV | quote }}
         value: {{ .Values.global.DDS_CONFIG | quote }}
       - name: ROS_DOMAIN_ID
         value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
       - name: RMF_FLEET_ADAPTER_EXEC
         value: {{ .Values.mir.RMF_FLEET_ADAPTER_EXEC | quote }}
       - name: RMF_FLEET_ADAPTER_CONFIG_FILE
         value: {{ .Values.mir.RMF_FLEET_ADAPTER_CONFIG_FILE | quote }}
       - name: RMF_FLEET_ADAPTER_NAV_GRAPH_FILE
         value: {{ .Values.global.NAV_GRAPH_MOUNT_PATH }}/{{ .Values.mir.RMF_FLEET_ADAPTER_NAV_GRAPH_FILE}}
     volumeMounts:
       - mountPath: /etc/cyclonedds
         name: cyclonedds-configmap
       - mountPath:  {{ .Values.global.NAV_GRAPH_MOUNT_PATH | quote }}
         name: nav-graph-configmap
       - mountPath:  /opt/rmf/install/fleet_adapter_mircw/share/fleet_adapter_mircw/config
         name: mir-configmap
 volumes:
   - name: cyclonedds-configmap
     configMap:
       name: cyclonedds-configmap
   - name: nav-graph-configmap
     configMap:
       name: nav-graph-configmap
   - name: mir-configmap
     configMap:
       name: mir-configmap