#---
#apiVersion: v1
#kind: Pod
#namespace: 
#metadata:
#  name: rmf-tinyrobot-fleet-adapter
#spec:
#  restartPolicy: Always
#  hostNetwork: true
#  containers:
#    - name: rmf-tinyrobot-fleet-adapter
#      image: {{ .Values.registryUrl }}/rmf_deployment_template/rmf-fleet-adapter
#      imagePullPolicy: Always
#      env:
#        - name: RMF_USE_SIM_TIME
#          value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
#        - name: CYCLONEDDS_URI
#          value: {{ .Values.global.CYCLONEDDS_URI | quote }}
#        - name: ROS_DOMAIN_ID
#          value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
#        - name: RMW_IMPLEMENTATION
#          value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
#        - name: RMF_FLEET_ADAPTER_CONTROL_TYPE
#          value: "full_control"
#        - name: RMF_FLEET_ADAPTER_FLEET_NAME
#          value: "tinyRobot"
#        - name: RMF_FLEET_ADAPTER_NAV_GRAPH_FILE
#          value: "/opt/rmf/install/rmf_demos_maps/share/rmf_demos_maps/maps/airport_terminal/nav_graphs/2.yaml"
#        - name: RMF_FLEET_ADAPTER_LINEAR_VELOCITY
#          value: "0.5"
#        - name: RMF_FLEET_ADAPTER_ANGULAR_VELOCITY
#          value: "0.6"
#        - name: RMF_FLEET_ADAPTER_LINEAR_ACCELERATION
#          value: "0.75"
#        - name: RMF_FLEET_ADAPTER_ANGULAR_ACCELERATION
#          value: "0.6"
#        - name: RMF_FLEET_ADAPTER_FOOTPRINT_RADIUS
#          value: "0.3"
#        - name: RMF_FLEET_ADAPTER_VICINITY_RADIUS
#          value: "1.0"
#        - name: RMF_FLEET_ADAPTER_DELAY_THRESHOLD
#          value: "15.0"
#        - name: RMF_FLEET_ADAPTER_RETRY_WAIT
#          value: "10.0"
#        - name: RMF_FLEET_ADAPTER_DISCOVERY_TIMEOUT
#          value: "60.0"
#        - name: RMF_FLEET_ADAPTER_PERFORM_DELIVERIES
#          value: "true"
#        - name: RMF_FLEET_ADAPTER_PERFORM_LOOP
#          value: "true"
#        - name: RMF_FLEET_ADAPTER_PERFORM_CLEANING
#          value: "true"
#        - name: RMF_FLEET_ADAPTER_BATTERY_VOLTAGE
#          value: "12.0"
#        - name: RMF_FLEET_ADAPTER_BATTERY_CAPACITY
#          value: "24.0"
#        - name: RMF_FLEET_ADAPTER_BATTERY_CHARGING_CURRENT
#          value: "5.0"
#        - name: RMF_FLEET_ADAPTER_MASS
#          value: "20.0"
#        - name: RMF_FLEET_ADAPTER_INERTIA
#          value: "10.0"
#        - name: RMF_FLEET_ADAPTER_FRICTION_COEFFICIENT
#          value: "0.22"
#        - name: RMF_FLEET_ADAPTER_AMBIENT_POWER_DRAIN
#          value: "20.0"
#        - name: RMF_FLEET_ADAPTER_TOOL_POWER_DRAIN
#          value: "0.0"
#        - name: RMF_FLEET_ADAPTER_DRAIN_BATTERY
#          value: "true"
#        - name: RMF_FLEET_ADAPTER_RECHARGE_THRESHOLD
#          value: "0.1"
#      volumeMounts:
#        - mountPath: /etc/cyclonedds
#          name: cyclonedds-configmap
#  volumes:
#    - name: cyclonedds-configmap
#      configMap:
#        name: cyclonedds-configmap
#
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: rmf-tinyrobot-robot-state-aggregator
#spec:
#  restartPolicy: Always
#  hostNetwork: true
#  containers:
#    - name: rmf-robot-state-aggregator
#      image: {{ .Values.registryUrl }}/rmf_deployment_template/rmf-robot-state-aggregator
#      imagePullPolicy: Always
#      env:
#        - name: RMF_USE_SIM_TIME
#          value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
#        - name: CYCLONEDDS_URI
#          value: {{ .Values.global.CYCLONEDDS_URI | quote }}
#        - name: ROS_DOMAIN_ID
#          value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
#        - name: RMW_IMPLEMENTATION
#          value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
#        - name: RMF_ROBOT_STATE_AGGREGATOR_FLEET_NAME
#          value: "tinyRobot"
#        - name: RMF_ROBOT_STATE_AGGREGATOR_ROBOT_PREFIX
#          value: "tinyRobot"
#        - name: RMF_ROBOT_STATE_AGGREGATOR_ROBOT_PREFIX
#          value: "tinyRobot"
#        - name: RMF_FAILOVER_MODE
#          value: "tinyRobot"
#          value: {{ .Values.global.RMF_FAILOVER_MODE | quote }}
#      volumeMounts:
#        - mountPath: /etc/cyclonedds
#          name: cyclonedds-configmap
#  volumes:
#    - name: cyclonedds-configmap
#      configMap:
#        name: cyclonedds-configmap
#        optional: true
