# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "leoScrub"
  fleet_manager:
    prefix: somekey
    user: somekey
    password: somekey
  limits:
    linear: [0.4, 0.2] # velocity, acceleration
    angular: [0.3, 0.35] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.5 # radius in m
    vicinity: 0.6 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 760.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: False
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: False
    delivery: False
    clean: True
    finishing_request: "nothing" # [park, charge, nothing]

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  LB00057:
    robot_config:
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      dock_home: [341.2186, 877.4262, 1.57079]
    rmf_config:
      robot_state_update_frequency: 0.5
      start:
        map_name: somekey
        # waypoint: "charger_deliverybot1" # Optional
        # orientation: 0.0 # Optional, radians
        waypoint: "dock_home"
        orientation: 1.57079
      charger:
        waypoint: "dock_home"
  # Configuration for the second robot in this fleet if there is a second robot
  # Uncomment if more than one robot exists.
  # deliverybot2:
  #   robot_config:
  #     max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  #   rmf_config:
  #     robot_state_update_frequency: 0.5
  #     start:
  #       map_name: "L1"
  #       # waypoint: "charger_deliverybot2" # Optional
  #       # orientation: 0.0 # Optional, radians
  #       waypoint: null
  #       orientation: null
  #     charger:
  #       waypoint: "charger_deliverybot2"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

reference_coordinates:
   rmf: [[12.9196, -14.9648],
         [38.8585, -16.5111],
         [32.8228, -58.7617],
         [8.1807, -58.8615]]
   robot: [[259.0360, 300.9160],
           [779.6770, 331.6570],
           [658.38360, 1178.8760],
           [164.2610, 1180.0010]]
