building_name: galen
levels:
  L1:
    lanes:
    - - 0
      - 1
      - {speed_limit: 0}
    - - 1
      - 0
      - {speed_limit: 0}
    - - 1
      - 2
      - {speed_limit: 0}
    - - 2
      - 1
      - {speed_limit: 0}
    - - 2
      - 3
      - {speed_limit: 0}
    - - 3
      - 2
      - {speed_limit: 0}
    - - 3
      - 4
      - {speed_limit: 0}
    - - 4
      - 3
      - {speed_limit: 0}
    - - 4
      - 5
      - {speed_limit: 0}
    - - 5
      - 4
      - {speed_limit: 0}
    - - 6
      - 7
      - {speed_limit: 0, undock_name: L1_1_pick_up}
    - - 7
      - 6
      - {dock_name: L1_1_pick_up, speed_limit: 0}
    - - 7
      - 8
      - {dock_name: L1_1_drop_off, speed_limit: 0}
    - - 8
      - 7
      - {speed_limit: 0, undock_name: L1_1_drop_off}
    - - 9
      - 10
      - {dock_name: L1_0_pick_up, speed_limit: 0}
    - - 10
      - 9
      - {speed_limit: 0, undock_name: L1_0_pick_up}
    - - 11
      - 9
      - {speed_limit: 0, undock_name: L1_0_drop_off}
    - - 9
      - 11
      - {dock_name: L1_0_drop_off, speed_limit: 0}
    - - 12
      - 13
      - {speed_limit: 0}
    - - 13
      - 12
      - {speed_limit: 0}
    - - 7
      - 12
      - {speed_limit: 0}
    - - 12
      - 7
      - {speed_limit: 0}
    - - 12
      - 14
      - {speed_limit: 0}
    - - 14
      - 12
      - {speed_limit: 0}
    - - 14
      - 15
      - {speed_limit: 0}
    - - 15
      - 14
      - {speed_limit: 0}
    - - 15
      - 16
      - {speed_limit: 0}
    - - 16
      - 15
      - {speed_limit: 0}
    - - 16
      - 9
      - {speed_limit: 0}
    - - 9
      - 16
      - {speed_limit: 0}
    - - 1
      - 17
      - {speed_limit: 0}
    - - 17
      - 1
      - {speed_limit: 0}
    - - 17
      - 18
      - {speed_limit: 0}
    - - 18
      - 17
      - {speed_limit: 0}
    - - 5
      - 12
      - {speed_limit: 0}
    - - 12
      - 5
      - {speed_limit: 0}
    vertices:
    - - 10.685042632391085
      - -2.193844398361281
      - {is_holding_point: true, name: mir_L1_1}
    - - 10.662169865417058
      - -5.617838533425355
      - {is_passthrough_point: false, name: ''}
    - - 10.650522478544673
      - -8.573067547553078
      - {is_passthrough_point: false, name: ''}
    - - 10.691288332598015
      - -10.838484294231613
      - {is_charger: false, is_parking_spot: false, is_passthrough_point: false, name: ''}
    - - 10.681244571454439
      - -12.951640998027688
      - {is_holding_point: true, name: mir_L1_0}
    - - 10.681244571454439
      - -14.95169988726584
      - {is_charger: true, is_holding_point: true, is_parking_spot: true, name: mir250_charger}
    - - 10.216277511454734
      - -21.560325917031097
      - {dock_name: L1_1_pick_up, name: L1_1_pick_up}
    - - 11.725289322261542
      - -21.560325917031097
      - {name: L1_1_entry}
    - - 10.229528524055924
      - -21.573576929632285
      - {dock_name: L1_1_drop_off, name: L1_1_drop_off}
    - - 24.670853422790593
      - -25.01512654635908
      - {name: L1_0_entry}
    - - 26.073941534142033
      - -25.068046195409693
      - {dock_name: L1_0_pick_up, name: L1_0_pick_up}
    - - 26.073941534142033
      - -25.068046195409693
      - {dock_name: L1_0_drop_off, name: L1_0_drop_off}
    - - 12.817105239516248
      - -20.97787217205779
      - {name: ''}
    - - 13.85642351449108
      - -20.9646211594566
      - {is_parking_spot: true, name: L1_mir_start}
    - - 14.452043870711428
      - -22.936912003180154
      - {name: ''}
    - - 17.819404697142392
      - -21.850666575299197
      - {name: ''}
    - - 19.06694111279961
      - -25.403288374084376
      - {name: ''}
    - - 9.393448709868764
      - -5.6299079270684755
      - {name: L1_liftB_wait}
    - - 7.188210128697543
      - -5.687385249243063
      - {lift: B, lift_cabin: B, name: ''}
  L5:
    lanes:
    - - 0
      - 1
      - {speed_limit: 0, undock_name: L5_01_drop_off}
    - - 1
      - 0
      - {dock_name: L5_01_drop_off, speed_limit: 0}
    - - 2
      - 1
      - {speed_limit: 0, undock_name: L5_01_pick_up}
    - - 1
      - 2
      - {dock_name: L5_01_pick_up, speed_limit: 0}
    - - 3
      - 4
      - {speed_limit: 0}
    - - 4
      - 3
      - {speed_limit: 0}
    - - 4
      - 5
      - {speed_limit: 0}
    - - 5
      - 4
      - {speed_limit: 0}
    - - 6
      - 3
      - {speed_limit: 0}
    - - 3
      - 6
      - {speed_limit: 0}
    - - 6
      - 7
      - {speed_limit: 0}
    - - 7
      - 6
      - {speed_limit: 0}
    - - 7
      - 8
      - {speed_limit: 0}
    - - 8
      - 7
      - {speed_limit: 0}
    - - 8
      - 9
      - {speed_limit: 0}
    - - 9
      - 8
      - {speed_limit: 0}
    - - 9
      - 10
      - {speed_limit: 0}
    - - 10
      - 9
      - {speed_limit: 0}
    - - 10
      - 11
      - {speed_limit: 0}
    - - 11
      - 10
      - {speed_limit: 0}
    - - 11
      - 12
      - {door_name: dormakaba_door1, speed_limit: 0}
    - - 12
      - 11
      - {door_name: dormakaba_door1, speed_limit: 0}
    - - 11
      - 13
      - {speed_limit: 0}
    - - 13
      - 11
      - {speed_limit: 0}
    - - 14
      - 15
      - {speed_limit: 0}
    - - 15
      - 14
      - {speed_limit: 0}
    - - 15
      - 3
      - {speed_limit: 0}
    - - 3
      - 15
      - {speed_limit: 0}
    - - 12
      - 16
      - {speed_limit: 0}
    - - 16
      - 12
      - {speed_limit: 0}
    - - 16
      - 17
      - {speed_limit: 0}
    - - 17
      - 16
      - {speed_limit: 0}
    vertices:
    - - -38.174124560574256
      - -19.239292253708317
      - {dock_name: L5_01_drop_off, name: L5_01_drop_off}
    - - -38.12245541666024
      - -17.819089373859
      - {name: L5_01_entry}
    - - -40.23167357534501
      - -17.830688059935056
      - {dock_name: L5_01_pick_up, name: L5_01_pick_up}
    - - 10.37051250551341
      - -5.631694571278769
      - {is_holding_point: false, is_parking_spot: false, is_passthrough_point: false,
        name: ''}
    - - 10.428417863069221
      - -2.7842403992881515
      - {name: ''}
    - - 13.444803914603035
      - -1.3049330625235673
      - {is_holding_point: true, is_parking_spot: true, name: mir_L5_0}
    - - 10.386473832270504
      - -8.517133154069207
      - {is_passthrough_point: false, name: ''}
    - - 10.386278595990753
      - -10.65941458243697
      - {name: ''}
    - - 10.428971524839149
      - -23.60820543310668
      - {name: corner}
    - - -4.365804872768798
      - -23.435934723150893
      - {name: corridor_mid}
    - - -16.325823474034642
      - -23.349189307057827
      - {name: mir_L5_1}
    - - -19.291110196531548
      - -23.317257124748046
      - {is_charger: false, is_parking_spot: true, name: door_test}
    - - -19.256319527361285
      - -18.001703144796277
      - {name: ''}
    - - -22.78557835545537
      - -23.31332957583098
      - {name: mir_L5_2}
    - - 7.379150602673526
      - -5.584005399552985
      - {lift: B, lift_cabin: B, name: ''}
    - - 9.435758389436522
      - -5.647793305049958
      - {name: ''}
    - - -34.7817202371323
      - -17.774987473661888
      - {name: ''}
    - - -39.87078542125755
      - -16.817382456452705
      - {name: mir_Lab_0}